CREATE TABLE channels(
  id VARCHAR(50) NOT NULL,
  name VARCHAR(50) NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT channels_pk PRIMARY KEY(id)
);

CREATE TABLE channel_users(
  user_id VARCHAR(50) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  channel_id VARCHAR(50) NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  CONSTRAINT channel_users_pk PRIMARY KEY(user_id, channel_id)
);
