CREATE TABLE users(
  id CHAR(50) NOT NULL,
  first_name CHAR(50) NULL,
  last_name CHAR(50) NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  role CHAR(15) NOT NULL,
  active boolean NOT NULL DEFAULT TRUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT users_pk PRIMARY KEY(id)
);
