/* eslint-disable max-len */
// Fake data
const users = [
  {
    id   : 1,
    role : 'admin',
  },
  {
    id   : 2,
    role : 'esthetician',
  },
  {
    id   : 3,
    role : 'customer',
  },
];

const surveyQuestions = [
  {
    id    : 1,
    title : 'We’re excited to meet you! What’s your first name?',
    type  : 'text',
  },
  {
    choices : [1, 2, 3],
    id      : 2,
    subtitle : 'Choose any that apply',
    title   : 'Do you love your current skincare routine?',
    type    : 'choice',
  },
  {
    choices : [4, 5, 6],
    id    : 3,
    title : 'Do you like to experiment with new skin care?',
    type  : 'choice',
  },
  {
    choices : [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
    id    : 4,
    title : 'What types of skin care products do you love to use the most?',
    type  : 'choice',
  },
  {
    choices : [20, 21, 22, 23, 24, 25],
    id    : 5,
    title : 'How would you describe your skin tone?',
    type  : 'choice',
  },
  {
    choices : [26, 27, 28],
    id    : 6,
    title : 'What type of environment do you live in?',
    type  : 'choice',
  },
  {
    choices : [29, 30, 31, 32],
    id    : 7,
    title : 'How would you describe your skin type?',
    type  : 'choice',
  },
  {
    choices : [33, 34, 35, 36, 37, 38, 39],
    id    : 8,
    title : 'What are your skin concerns?',
    type  : 'choice',
  },
  {
    choices : [40, 41, 42, 43],
    id    : 9,
    title : 'Do you often struggle with your skin?',
    type  : 'choice',
  },
  {
    choices : [44, 45, 46, 47, 48],
    id    : 10,
    title : 'UV light is the #1 cause in premature aging, do you diligently wear sunscreen?',
    type  : 'choice',
  },
  {
    choices : [49, 50, 51, 52],
    id    : 11,
    title : 'Do you have any sensitivities to ingredients or fragrance?',
    type  : 'choice',
  },
  {
    choices : [53, 54, 55, 56, 57, 58, 59, 60, 61],
    id    : 12,
    title : 'Where do you usually shop for beauty products?',
    type  : 'choice',
  },
  {
    choices : [62, 63, 64, 65],
    id    : 13,
    title : 'Are you currently seeing a Dermatologist or Esthetician?',
    type  : 'choice',
  },
  {
    choices : [66, 67, 68],
    id    : 14,
    title : 'What type of skin care routine are you looking for?',
    type  : 'choice',
  },
  {
    choices : [69, 70, 71, 72, 73],
    id    : 15,
    title : 'Age helps us understand what products would be best for you! What age group do you fall under?',
    type  : 'choice',
  },
  {
    choices : [74, 75, 76, 77],
    id    : 16,
    title : 'What’s the monthly budget you’re willing to invest in a new skin care routine?',
    type  : 'choice',
  },
];

const surveyQuestionChoices = {
  1: { id: 1, title: 'I love it! I wouldn’t change much of it' },
  2: { id: 2, title: 'It’s ok, some products are working, some aren’t' },
  3: { id: 3, title: 'Not at all! Nothing seems to work for me. ' },
  4: { id: 4, title: 'Yes! I try new products all of the time' },
  5: { id: 5, title: 'Sometimes, when products don’t work' },
  6: { id: 6, title: 'Rarely, I like the products I use' },
  7: { id: 7, title: 'Cleansers' },
  8: { id: 8, title: 'Cleansing oils' },
  9: { id: 9, title: 'Sheet masks' },
  10: { id: 10, title: 'Wash off masks' },
  11: { id: 11, title: 'Exfoliators' },
  12: { id: 12, title: 'Serums' },
  13: { id: 13, title: 'Face oils' },
  14: { id: 14, title: 'Toners and Mists' },
  15: { id: 15, title: 'Eye treatments' },
  16: { id: 16, title: 'Anti-aging treatments' },
  17: { id: 17, title: 'Peels' },
  18: { id: 18, title: 'Acne treatments' },
  19: { id: 19, title: 'Other - tell us more!' },
  20: { id: 20, title: 'Very fair' },
  21: { id: 21, title: 'Fair' },
  22: { id: 22, title: 'Medium' },
  23: { id: 23, title: 'Medium-Olive' },
  24: { id: 24, title: 'Dark' },
  25: { id: 25, title: 'Very Dark' },
  26: { id: 26, title: 'The weather is humid' },
  27: { id: 27, title: 'The weather is dry' },
  28: { id: 28, title: 'Neither humid or dry' },
  29: { id: 29, title: 'Oily, I produce oil all over, including my t-zone' },
  30: { id: 30, title: 'Normal, neither very oily or very dry' },
  31: { id: 31, title: 'Dry, I produce little to no oil' },
  32: { id: 32, title: 'Combination, I’m dry in some areas, and oily in others' },
  33: { id: 33, title: 'Redness' },
  34: { id: 34, title: 'Fine lines & wrinkles' },
  35: { id: 35, title: 'Oiliness & large pores' },
  36: { id: 36, title: 'Acne & blemishes' },
  37: { id: 37, title: 'Dryness & dehydration' },
  38: { id: 38, title: 'Hyperpigmentation' },
  39: { id: 39, title: 'Other - tell us more' },
  40: { id: 40, title: 'No, just interested in trying new products' },
  41: { id: 41, title: 'Recently, in the last month' },
  42: { id: 42, title: 'A while, 3-6 months' },
  43: { id: 43, title: 'Seems like forever! Over a year.' },
  44: { id: 44, title: 'Never' },
  45: { id: 45, title: 'Rarely' },
  46: { id: 46, title: 'Sometimes' },
  47: { id: 47, title: 'Often' },
  48: { id: 48, title: 'Always' },
  49: { id: 49, title: 'No, not that I’m aware of' },
  50: { id: 50, title: 'Yes, I’m often sensitive to products, but I’m not sure why' },
  51: { id: 51, title: 'Yes, I have a sensitivity to fragrance' },
  52: { id: 52, title: 'Yes, I have other sensitivities (tell us more - open field)' },
  53: { id: 53, title: 'Sephora' },
  54: { id: 54, title: 'ULTA' },
  55: { id: 55, title: 'Target' },
  56: { id: 56, title: 'Prestige Retailers: Neiman Marcus, Net-A-Porter' },
  57: { id: 57, title: 'Department Stores: Nordstrom, Macy’s' },
  58: { id: 58, title: 'Online Retailers: DermStore, SkinStore, Amazon' },
  59: { id: 59, title: 'TV: QVC, HSN' },
  60: { id: 60, title: 'Dermatologist' },
  61: { id: 61, title: 'Esthetician' },
  62: { id: 62, title: 'Yes, Dermatologist ' },
  63: { id: 63, title: 'Yes, Esthetician ' },
  64: { id: 64, title: 'Yes, Both' },
  65: { id: 65, title: 'No, I’m not getting treated by either' },
  66: { id: 66, title: 'Basic, just 1 or 2 products that will help with specific concerns.' },
  67: { id: 67, title: 'Essentials, I prefer a simple routine, but open to additional products that may enhance results.' },
  68: { id: 68, title: 'Complete, I want the best results and have the time to invest in all of the products that will help me!' },
  69: { id: 69, title: 'Under 18' },
  70: { id: 70, title: '19-29' },
  71: { id: 71, title: '30-39' },
  72: { id: 72, title: '40-59' },
  73: { id: 73, title: '60+' },
  74: { id: 74, title: '$50-$75' },
  75: { id: 75, title: '$75-$125' },
  76: { id: 76, title: '$125-$175' },
  77: { id: 77, title: '$175+' },
};


export default {
  Query: {
    surveyQuestions: () => surveyQuestions,
    users: () => users,
  },

  SurveyQuestion: {
    choices: (question) => {
      if (!Array.isArray(question.choices)) return null;
      return question.choices.map((id) => surveyQuestionChoices[id]);
    },
  },
};
/* eslint-enable max-len */
